export enum F1TVPlatform {
  BIG_SCREEN_DASH = 'BIG_SCREEN_DASH',
  BIG_SCREEN_HLS = 'BIG_SCREEN_HLS',
  MOBILE_DASH = 'MOBILE_DASH',
  MOBILE_HLS = 'MOBILE_HLS',
  TABLET_DASH = 'TABLET_DASH',
  TABLET_HLS = 'TABLET_HLS',
  WEB_DASH = 'WEB_DASH',
  WEB_HLS = 'WEB_HLS',
};
