name: Build packages

on:
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, win32, darwin]
        arch: [x64, arm64, ia32]
        exclude:
          - platform: darwin
            arch: ia32
          - platform: win32
            arch: arm64
          - platform: linux
            arch: arm64
          - platform: linux
            arch: ia32

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          check-latest: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          check-latest: true

      - name: Install dependencies
        run: npm install

      - name: Build package
        env:
          CASTLABS_EVS_USERNAME: ${{ secrets.CASTLABS_EVS_USERNAME }}
          CASTLABS_EVS_PASSWORD: ${{ secrets.CASTLABS_EVS_PASSWORD }}
        run: npm run package -- --platform ${{ matrix.platform }} --arch ${{ matrix.arch }}

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: eXViewer-${{ matrix.platform }}-${{ matrix.arch }}
          path: out/eXViewer-${{ matrix.platform }}-${{ matrix.arch }}/
          if-no-files-found: error
          compression-level: 9
